import {defineConfig} from 'vitepress'

export const en = defineConfig({
    lang: "en-US",
    description: "A library made for Minecraft particle generation",
    themeConfig: {
        nav: [
            {text: 'Get Start', link: '/en/guide/'},
            {text: 'API Document', link: '/en/api/'},
            {text: 'Demo', link: '/en/demo/'},
        ],
        footer: {
            message: 'Documentation built with <a href="https://vitepress.dev/">VitePress</a> | API references generated by <a href="https://github.com/LiteyukiStudio/litedoc">litedoc</a>',
            copyright: 'Copyright (C) 2020-2024 SnowyKami. All Rights Reserved'
        },
        outline: {
            label: "On this page",
            level: [2, 6]
        }
    },
})